<?php
$ModName="問與答";
$MainFileName01="QAMessage.php";
$ModifyFileName01="QAMessage_Add_Modify.php";
$DatabaseName01="productquestion";
$DatabaseName01_S="productquestion";
$ModName2="回覆問與答";
$MainFileName02="QAMessageReply.php";
$ModifyFileName02="";
$DatabaseName02="productquestionreply";
$DatabaseName02_S="productquestionreply";
$Tree_id="60";
$Tree_Name="問與答";
$Tree_View="true";
$Menu_id="6010";
$Menu_Name="問與答";
$Menu_Path="../form/QAMessage/QAMessage.php";
$Menu_File="QAMessage.php";
$Menu_View="true";
$SqlView="true";
?>