<?php
$ModName="運費管理";
$MainFileName01="Fare.php";
$ModifyFileName01="Fare_Add_Modify.php";
$DatabaseName01="fare";
$DatabaseName01_S="fare";
$Tree_id="8050";
$Tree_Name="運費管理";
$Tree_View="true";
$Menu_id="8050";
$Menu_Name="運費管理";
$Menu_Path="../form/Fare/Fare.php";
$Menu_File="Fare.php";
$Menu_View="true";
$SqlView="true";
?>