<?php
$ModName="職業";
$MainFileName01="MemberJob.php";
$ModifyFileName01="MemberJob_Add_Modify.php";
$DatabaseName01="member_job";
$DatabaseName01_S="member_job";
$Tree_id="80";
$Tree_Name="前台管理";
$Tree_View="true";
$Menu_id="8030";
$Menu_Name="職業";
$Menu_Path="../form/MemberJob/MemberJob.php";
$Menu_File="MemberJob.php";
$Menu_View="true";
$SqlView="true";
?>