<?php
$ModName="聯絡我們";
$MainFileName01="Contact.php";
$ModifyFileName01="Contact_Add_Modify.php";
$DatabaseName01="contact";
$DatabaseName01_S="contact";
$ModName2="回覆聯絡我們";
$MainFileName02="ContactReply.php";
$ModifyFileName02="";
$DatabaseName02="contactreply";
$DatabaseName02_S="contactreply";
$Tree_id="70";
$Tree_Name="聯絡我們";
$Tree_View="true";
$Menu_id="7010";
$Menu_Name="聯絡我們";
$Menu_Path="../form/Contact/Contact.php";
$Menu_File="Contact.php";
$Menu_View="true";
$SqlView="true";
?>