<?php
$ModName="最新消息";
$MainFileName01="News.php";
$ModifyFileName01="News_Add_Modify.php";
$DatabaseName01="news";
$DatabaseName01_S="news";
$MaxPicWidth="660";
$ModName2_1="相關連結";
$MainFileName02_1="NewsLink.php";
$ModifyFileName02_1="NewsLink_Add_Modify.php";
$DatabaseName02_1="newslink";
$DatabaseName02_1_S="newslink";
$ModName2_2="檔案下載";
$MainFileName02_2="NewsFile.php";
$ModifyFileName02_2="NewsFile_Add_Modify.php";
$DatabaseName02_2="newsfile";
$DatabaseName02_2_S="newsfile";
$UploadFilePath="../../../files/News/Files/";
$LimitAmount="0";
$Tree_id="20";
$Tree_Name="最新消息";
$Menu_id="2020";
$Menu_Name="最新消息";
$Menu_Path="../form/News/News.php";
$Menu_File="News.php";
$SqlView="true";
?>